### ISSUE TITLE
Missing information from JSON file

### ISSUE THREAD

**Issue by ignasiusharvey** [virgs/medium-next-gen-stats#3] opened 2020-07-26 10:53 UTC
Hi, great job for next-gen-stats!

I had used this tool and I notice there's an update.
On my previous usage, the JSON file contains information about `readingTime`.
But it looks like it's missing now on the new JSON file.
Would be great if that information is retained.

**Comment by virgs** [comment] 2020-07-27 13:36
Hmm. I believe the issue is fixed in v1.0.16.
Can you confirm that?

**Comment by ignasiusharvey** [comment] 2020-07-27 16:01
I cloned the v1.0.16 and looks like it's not fixed yet.

**Comment by virgs** [comment] 2020-07-27 16:27
This looks weird.
This is a piece of the content of one of the files I get when I hit the download button:
```
[
  {
    "postId": "9c26d20b1777",
    "slug": "a-vida-mais-difícil",
    "previewImage": {
      "id": "0*cNMDhiWytcg3ZpJt.jpeg",
      "originalWidth": 1500,
      "originalHeight": 1500,
      "isFeatured": true
    },
    "title": "A Vida Mais Difícil",
    "creatorId": "5e1d07b76ff4",
    "collectionId": "",
    "upvotes": 6,
    "views": 26,
    "reads": 14,
    "createdAt": 1567388130804,
    "firstPublishedAt": 1595090976651,
    "visibility": 0,
    "firstPublishedAtBucket": "July 2020",
    "readingTime": 4,
    "syndicatedViews": 0,
    "claps": 57,
    "updateNotificationSubscribers": 0,
    "isSeries": false,
    "internalReferrerViews": 14,
    "friendsLinkViews": 0,
    "type": "PostStat",
    "id": "9c26d20b1777"
  },
...
```

Are you sure you're checking `mngs-posts-summary.json` file?

**Comment by ignasiusharvey** [comment] 2020-07-28 03:49
I made sure the version is 1.0.16 on my browser. I clicked the download button and only `medium-next-generation-stats.json` is downloaded.

**Comment by virgs** [comment] 2020-07-28 12:57
Ok. Thanks for the report.
I'll investigate that and inform you as soon as I have updates.

**Comment by virgs** [comment] 2020-07-30 12:09
@ignasiusharvey Can you check it now?
v.17 was released, make sure you refresh your cache before trying.

**Comment by ignasiusharvey** [comment] 2020-07-31 15:05
@virgs I believe the issue is fixed, the information is already there.
Thank you!

**Closed as completed** 2020-07-31 17:23 UTC
